name: OpenStudioPress
options:
  bundleIdPrefix: com.leandroagustinhallak
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  developmentLanguage: en
settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    GENERATE_INFOPLIST_FILE: YES
    INFOPLIST_FILE: OpenStudioPress/Info.plist
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    PRODUCT_BUNDLE_IDENTIFIER: com.leandroagustinhallak.openstudiopress
    PRODUCT_NAME: OpenStudioPress
    DEVELOPMENT_TEAM: "PXX4K82S62"
    CODE_SIGN_STYLE: Automatic
    SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: NO
    SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
    SUPPORTS_MACCATALYST: NO
targets:
  OpenStudioPress:
    type: application
    platform: iOS
    sources:
      - path: OpenStudioPress
        excludes:
          - Info.plist
    resources:
      - path: OpenStudioPress/Assets.xcassets
      - path: OpenStudioPress/PrivacyInfo.xcprivacy
    settings:
      base:
        TARGETED_DEVICE_FAMILY: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        INFOPLIST_KEY_CFBundleDisplayName: Open Studio Press
        PRODUCT_BUNDLE_IDENTIFIER: com.leandroagustinhallak.openstudiopress
        PRODUCT_DISPLAY_NAME: Open Studio Press
        CODE_SIGN_ENTITLEMENTS: Config/OpenStudioPress.entitlements
        DEVELOPMENT_TEAM: "PXX4K82S62"
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: NO
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
        SUPPORTS_MACCATALYST: NO
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
        INFOPLIST_KEY_UIRequiresFullScreen: YES
  OpenStudioPressUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: OpenStudioPressUITests
    dependencies:
      - target: OpenStudioPress
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_FILE: ""
        PRODUCT_BUNDLE_IDENTIFIER: com.leandroagustinhallak.openstudiopress.uitests
        PRODUCT_NAME: OpenStudioPressUITests
        PRODUCT_MODULE_NAME: OpenStudioPressUITests
        DEVELOPMENT_TEAM: "PXX4K82S62"
        TEST_TARGET_NAME: OpenStudioPress
        CODE_SIGN_ENTITLEMENTS: ""

schemes:
  OpenStudioPress:
    build:
      targets:
        OpenStudioPress: all
        OpenStudioPressUITests: [test]
    test:
      targets:
        - OpenStudioPressUITests
